### ISSUE TITLE
Selenium Firefox Driver

### ISSUE THREAD

**Issue by lukeroberts-tv** [SethRzeszutek/LinkedIn-Bot#1]
Please add support for Firefox Driver ;)

**Comment by SethRzeszutek** [comment]
I will do by best! Would you prefer it just another setting in `configure.py` or a prompt that you have to enter each time?

**Comment by SethRzeszutek** [comment]
I added somewhat of support to it for Mac at least, need to do more testing on Windows...

**Comment by SethRzeszutek** [comment]
This should be fixed! Let me know if there is still an issue!
